In [ ]:
import numpy as np
matrix1 = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
matrix2 = np.array([[9, 8, 7],
 [6, 5, 4],
 [3, 2, 1]])


In [ ]:
matrix_sum = np.add(matrix1, matrix2)
matrix_diff = np.subtract(matrix1, matrix2)

print("Matrix Addition:")
print(matrix_sum)

print("\nMatrix Subtraction:")
print(matrix_diff)


Matrix Addition:

[[10 10 10]

 [10 10 10]

 [10 10 10]]



Matrix Subtraction:

[[-8 -6 -4]

 [-2  0  2]

 [ 4  6  8]]


In [ ]:
matrix1 = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
 [6, 5, 4],
 [3, 2, 1]])

In [ ]:
matrix_product = np.dot(matrix1, matrix2)
matrix_division = np.divide(matrix1, matrix2)

print("Matrix Multiplication:")
print(matrix_product)

print("\nElement-wise Matrix Division:")
print(matrix_division)


Matrix Multiplication:

[[ 30  24  18]

 [ 84  69  54]

 [138 114  90]]



Element-wise Matrix Division:

[[0.11111111 0.25       0.42857143]

 [0.66666667 1.         1.5       ]

 [2.33333333 4.         9.        ]]


In [ ]:
# In the first Python program, we leverage NumPy to perform addition and subtraction of matrices.
# Two matrices are defined, and the NumPy operators '+' and '-' are used to carry out element-wise addition and subtraction, respectively.
# This showcases the ease with which NumPy handles basic linear algebra operations, providing a concise and efficient way to manipulate matrices.
# The resulting matrices after addition and subtraction are displayed, demonstrating the outcomes of these operations.
# The second program focuses on matrix multiplication and division using NumPy. It defines two matrices,
# and the NumPy function `dot` is employed for multiplication, providing the product of the matrices.
# Additionally, matrix division is demonstrated by utilizing the `inv` function to find the inverse of one matrix and multiplying it with the other.
# These operations showcase the versatility of NumPy in performing fundamental linear algebra computations, essential for various scientific
# and engineering applications.