In [ ]:
import numpy as np

matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

In [ ]:
matrix_transpose = np.transpose(matrix)

print("Original Matrix:")
print(matrix)

print("\nTransposed Matrix:")
print(matrix_transpose)


Original Matrix:

[[1 2 3]

 [4 5 6]

 [7 8 9]]



Transposed Matrix:

[[1 4 7]

 [2 5 8]

 [3 6 9]]


In [ ]:
A = np.array([[2, 1],
 [1, 3]])

B = np.array([5, 8])

In [ ]:
x = np.linalg.solve(A, B)

print("Solution:")
print(x)

Solution:

[1.4 2.2]


In [ ]:
# In the first Python program, we utilize NumPy to find the transpose of a given matrix.
# The matrix is defined, and the NumPy function `transpose` is employed to compute its transpose.
# This operation switches the rows and columns of the matrix, resulting in a new matrix with columns becoming rows and vice versa.
# The original and transposed matrices are then displayed, showcasing the transformation.
# The second program delves into solving linear systems of equations using matrices and vectors.
# It constructs a coefficient matrix 'A' and a right-hand side vector 'B'.
# The NumPy function `linalg.solve` efficiently computes the solution vector 'x' for the linear system Ax = B.
# The resulting solution provides values for the variables in the system that satisfy all the equations.
# This demonstrates the application of linear algebra techniques to solve real-world problems involving systems of linear equations.